<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2024-10-16 16:05:05
 */
return [
    'all' => [
        'class' => 'frontend\\assets\\AppAsset',
        'basePath' => '@webroot/',
        'baseUrl' => '@web/',
        'jsOptions' => [
            'defer' => 'defer',
        ],
        'js' => [
            'assets/all-c2f6ef55799585e9379d7375891b7289.min.js',
        ],
        'css' => [
            'assets/all-402506f5862d448755f6964170960d26.min.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'frontend\\assets\\NpmAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'frontend\\assets\\FancyboxAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'frontend\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'frontend\\assets\\NpmAsset',
            'frontend\\assets\\FancyboxAsset',
            'all',
        ],
    ],
];